### ISSUE TITLE
Doesn't work, please help

### ISSUE THREAD

**Issue by naveedrocks1** [cdv-dev/Android-ATM-searcher#5]
Hi there, Can you please tell me why I can't seen any results? It just says Nothing found. Does this work only in few areas? and if I wish to make it show nerby hotels or something else can I do it? if yes what do I need to change? Thanks in Advance

**Comment by cdv-dev** [comment]
I had some problems at the server last week. I fixed it a few hours ago. Now you can see not empty list.

> if I wish to make it show nerby hotels or something else can I do it? if yes what do I need to change?

Yes, but if you have server/API that will be return hotels or something else. Currently, my server returns only ATMs. But we can talk about your idea, and may be I could implement it on my server or help you to create new app.

**Comment by naveedrocks1** [comment]
Thank you, but app is still showing Nothing Found. can you give me your email? so that I can mail you. Thank you.

**Comment by naveedrocks1** [comment]
Sorry it does show ATMs now, but they seem to be Russian ATMs it should show local ATMs or am I wrong?

**Comment by cdv-dev** [comment]
No, it`s all right. Currently app shows only atms of one bank of Ukraine. I want to add some other banks, but I still haven`t found any method that let me to get atms of other banks and countries :( 

If you know how to get list of atms of other banks (may be in your country), please, tell. My email dmitriy.chernysh@gmail.com , will be glad to communicate with you :)
